// Code generated by stag. DO NOT EDIT.
// Source file: user.go

package sample

var User_DB = struct {
	FirstName       string
	LastName        string
	Age             string
	DOB             string
	JSONBlankName   string
	ID              string
	AllDBFieldNames []string
}{

	FirstName:       "first_name",
	LastName:        "last_name",
	Age:             "age_years",
	DOB:             "bday",
	JSONBlankName:   "json_blank_name",
	ID:              "pk_id",
	AllDBFieldNames: []string{"first_name", "last_name", "age_years", "bday", "json_blank_name", "pk_id"},
}

func IsValidUser_DBField(f string) bool {
	for _, fn := range User_DB.AllDBFieldNames {
		if fn == f {
			return true
		}
	}
	return false
}

var PowerUser_DB = struct {
	SpecialPower    string
	JSONSkip        string
	DBBlankName     string
	FirstName       string
	LastName        string
	Age             string
	DOB             string
	JSONBlankName   string
	ID              string
	AllDBFieldNames []string
}{

	SpecialPower:    "super_power",
	JSONSkip:        "json_skip",
	DBBlankName:     "DBBlankName",
	FirstName:       "first_name",
	LastName:        "last_name",
	Age:             "age_years",
	DOB:             "bday",
	JSONBlankName:   "json_blank_name",
	ID:              "pk_id",
	AllDBFieldNames: []string{"super_power", "json_skip", "DBBlankName", "first_name", "last_name", "age_years", "bday", "json_blank_name", "pk_id"},
}

func IsValidPowerUser_DBField(f string) bool {
	for _, fn := range PowerUser_DB.AllDBFieldNames {
		if fn == f {
			return true
		}
	}
	return false
}
