// Code generated by stag. DO NOT EDIT.
// Source file: ../sample/user.go

package sample

var User_JSON = struct {
	FirstName         string
	LastName          string
	Age               string
	DOB               string
	DBSkip            string
	JSONBlankName     string
	ID                string
	AllJSONFieldNames []string
}{

	FirstName:         "fName",
	LastName:          "lName",
	Age:               "age",
	DOB:               "dob",
	DBSkip:            "dbSkip",
	JSONBlankName:     "JSONBlankName",
	ID:                "id",
	AllJSONFieldNames: []string{"fName", "lName", "age", "dob", "dbSkip", "JSONBlankName", "id"},
}

func IsValidUser_JSONField(f string) bool {
	for _, fn := range User_JSON.AllJSONFieldNames {
		if fn == f {
			return true
		}
	}
	return false
}

var PowerUser_JSON = struct {
	SpecialPower      string
	DBBlankName       string
	FirstName         string
	LastName          string
	Age               string
	DOB               string
	DBSkip            string
	JSONBlankName     string
	ID                string
	AllJSONFieldNames []string
}{

	SpecialPower:      "superPower",
	DBBlankName:       "dbBlanker",
	FirstName:         "fName",
	LastName:          "lName",
	Age:               "age",
	DOB:               "dob",
	DBSkip:            "dbSkip",
	JSONBlankName:     "JSONBlankName",
	ID:                "id",
	AllJSONFieldNames: []string{"superPower", "dbBlanker", "fName", "lName", "age", "dob", "dbSkip", "JSONBlankName", "id"},
}

func IsValidPowerUser_JSONField(f string) bool {
	for _, fn := range PowerUser_JSON.AllJSONFieldNames {
		if fn == f {
			return true
		}
	}
	return false
}
